In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,])
b = a+5
print(b)

[6 7 8]


In [4]:
a = [1,2,3,4]
avg = sum(a)/len(a)
print(avg)

2.5


In [5]:
a = np.array([ 
    [10,20,30],

    [50,60,70]
])
print(a)
type(a)

[[10 20 30]
 [50 60 70]]


numpy.ndarray

In [6]:
a = np.array([ 10,20,30])
print(np.mean(a))

20.0


In [7]:
a = np.array([ 10,20,30])
print(np.mean(a))

20.0


In [8]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [9]:
a =np.array([
    [1,2,3],
    [4,5,6]
])
print(a.ndim)
    

2


In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a = [10,20,30,40,50]
array1 = np.array(a)
print(array1)
type(array1)

[10 20 30 40 50]


numpy.ndarray

In [12]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])
print(a)
type(a)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [13]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [14]:
a = np.arange(11,17).reshape((2,3))
print(a)

[[11 12 13]
 [14 15 16]]


In [16]:
a = np.array([[[
    [11,22,33,],
    [54,65,76,],
    [95,13,60,]
]]])
print(a.size)

9


In [17]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])
print(a.dtype)

int64


In [18]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])
print(a.itemsize)

8


In [19]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
   ])
print(a.ndim)

2


In [20]:
a = np.arange(5,51,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50]


In [21]:
arr = np.ones((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
arr = np.linspace(0,1,6)
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [23]:
import numpy as np
arr = np.array([4,5,60])
arr2 = np.array([1,2,3])
print(arr+arr2)
print(arr-arr2)
print(arr*arr2)
print(arr/arr2)
print(arr**arr2)

[ 5  7 63]
[ 3  3 57]
[  4  10 180]
[ 4.   2.5 20. ]
[     4     25 216000]


In [24]:
marks = np.array([10,20,30,40,50])
print(marks.sum())
print(marks.mean())
print(marks.max())
print(marks.min())

150
30.0
50
10


In [25]:
a = np.array([10,20,30])
b = np.array([40,50,60])
c = np.concatenate((a,b))
print(c)

[10 20 30 40 50 60]


In [26]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimensions:", a.ndim)
print("Data type:", a.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [28]:
a = np.array([10,20,30,40,50])
middle_element=a[len(a)//2]
print(middle_element)

30


In [29]:
a = np.array([10, -5, 20, -3, 30])
a[a < 0] = 0
print(a)

[10  0 20  0 30]


In [30]:
a = np.array([ 1,2,3,4,2,3,5,6,4])
print(np.where(a==2))

(array([1, 4]),)


In [31]:
a = np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [32]:
a = np.array([[1,2,3],[4,5,6]])
b = a.flatten()
b  [0] = 100
print (a)
print(b)


[[1 2 3]
 [4 5 6]]
[100   2   3   4   5   6]


In [33]:
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
b  [0] = 100
print (a)
print(b)

[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6]


In [34]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


In [35]:
a = np.random.rand(5)
print(a)

[0.91216852 0.30326505 0.47182121 0.08550991 0.66640336]


In [36]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(8,)
8
int64


In [37]:
a = np.arange(1,21,2)
print(a)
print(a.shape)

[ 1  3  5  7  9 11 13 15 17 19]
(10,)


In [38]:
a = np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [39]:
a = np.zeros((3,3))
print(a)
print(a.ndim)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(3, 3)


In [40]:
a = np.full((2,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [41]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
import numpy as np
a = np.random.rand(5)
print(a)

[0.54795875 0.8571391  0.73076531 0.58271067 0.91034085]


In [44]:
a = np.random.rand(3,3)
print(a)

[[0.60640116 0.19002215 0.26407191]
 [0.30357721 0.31753905 0.3309906 ]
 [0.8617965  0.46599537 0.75141691]]


In [45]:
a = np.random.randint(10,15,10)
print(a)

[11 14 11 11 14 13 13 13 14 10]


In [46]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5 6]
1
(6,)


In [48]:
arr = np.random.randint(1, 101, size=(2, 4))
print("Array:")
print(arr)
print("Data type:", arr.dtype)

Array:
[[14 62 49 78]
 [26 50 47 77]]
Data type: int32


In [49]:
a = np.array([1,2,3,4,5])
b = a.copy()
b[0]=100
print(a)
print(b)

[1 2 3 4 5]
[100   2   3   4   5]


In [50]:
a = np.array([1,2,3,4,5])
b = a.view()
b[0]=100
print(a)
print(b)

[100   2   3   4   5]
[100   2   3   4   5]


In [51]:
a = np.arange(100,120)
print(a)
print(a.shape)
print(a.size)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]
(20,)
20


In [52]:
a = np.linspace(0,1,15)
print(a)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [53]:
a = np.ones((2,3),dtype=int)
print(a)
print(a.dtype)


[[1 1 1]
 [1 1 1]]
int64


In [54]:
a = np.zeros((3,3),dtype=float)
print(a)
print(a.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9


In [55]:
arr = np.random.randint(0, 10, size=(2, 5))
print("Array:")
print(arr)

print("Shape:", arr.shape)

Array:
[[6 8 5 2 5]
 [0 6 9 8 5]]
Shape: (2, 5)
